# Generate Clones for Asteroids
This notebook demonstrates how to query JPL CNEOS API for orbital elements and covariances and generate clones from that covariance matrix. The clones' states are given in orbital elements and are then converted to Cartesian states that can be used for uncertainty propagation.

S. Eggl 20200123

In [1]:
import numpy as np
import jpl_query
from scipy.linalg import cholesky

In [5]:
#TARGET ASTEROID IDENTIFIER FOR JPL QUERUY
tname='Duende'

In [6]:
#QUERY JPL FOR ORBITAL ELEMENTS AND COVARIANCE MATRIX
data=jpl_query.query_cometary_ele_and_cov(tname)

In [7]:
#EPOCH FOR ORBITAL ELEMENTS AND COVARIANCE MATRIX (JD)
epoch=data[0]

In [8]:
#COMETARY ORBITAL ELEMENTS [e,q,tp(JD),node(deg),peri(deg),inc(deg)]
com=np.array(data[1])

In [9]:
com

array([1.08129352e-01, 8.93492625e-01, 2.45626155e+06, 1.47262479e+02,
       2.71086261e+02, 1.03372996e+01])

In [10]:
#COVARIANCE MATRIX
cov=np.array(data[2])

In [11]:
cov

array([[ 1.22427066e-15, -1.21595471e-15, -7.70335932e-15,
         7.27276618e-16, -1.49591848e-13, -3.61762539e-14],
       [-1.21595471e-15,  1.21014550e-15,  8.78586162e-15,
        -7.17810854e-16,  1.50033328e-13,  3.59520167e-14],
       [-7.70335932e-15,  8.78586162e-15,  6.00186647e-13,
         5.81889730e-15,  1.63466838e-12,  2.85535705e-13],
       [ 7.27276618e-16, -7.17810854e-16,  5.81889730e-15,
         1.11320495e-14, -8.87319114e-14,  3.01011899e-14],
       [-1.49591848e-13,  1.50033328e-13,  1.63466838e-12,
        -8.87319114e-14,  1.91672708e-11,  4.42994470e-12],
       [-3.61762539e-14,  3.59520167e-14,  2.85535705e-13,
         3.01011899e-14,  4.42994470e-12,  1.33606512e-12]])

## Create Clones from Covariance Matrix

In [12]:
nclones=1000
clones=np.random.multivariate_normal(com, cov, nclones)

In [13]:
clones

array([[1.08129327e-01, 8.93492651e-01, 2.45626155e+06, 1.47262479e+02,
        2.71086266e+02, 1.03372994e+01],
       [1.08129406e-01, 8.93492570e-01, 2.45626155e+06, 1.47262479e+02,
        2.71086254e+02, 1.03372986e+01],
       [1.08129344e-01, 8.93492632e-01, 2.45626155e+06, 1.47262479e+02,
        2.71086262e+02, 1.03373003e+01],
       ...,
       [1.08129374e-01, 8.93492603e-01, 2.45626155e+06, 1.47262479e+02,
        2.71086259e+02, 1.03372998e+01],
       [1.08129359e-01, 8.93492617e-01, 2.45626155e+06, 1.47262479e+02,
        2.71086260e+02, 1.03372990e+01],
       [1.08129275e-01, 8.93492698e-01, 2.45626155e+06, 1.47262479e+02,
        2.71086269e+02, 1.03373024e+01]])

## Convert Clones from Cometary Elements to Cartesian States (heliocentric!)

In [14]:
#Epoch
data[0]

2456165.5

In [15]:
clones_cart=[]
for cl in clones:
    clones_cart.append(jpl_query.cometary2cartesian(data[0],cl))

In [17]:
#List of Cartesian states
clones_cart

[array([ 0.68329945, -0.7578357 ,  0.04887248,  0.01115044,  0.01227683,
        -0.00298354]),
 array([ 0.68329922, -0.75783593,  0.04887254,  0.01115044,  0.01227682,
        -0.00298353]),
 array([ 0.68329939, -0.75783575,  0.0488725 ,  0.01115044,  0.01227683,
        -0.00298354]),
 array([ 0.68329939, -0.75783577,  0.0488725 ,  0.01115044,  0.01227683,
        -0.00298353]),
 array([ 0.68329924, -0.75783591,  0.04887253,  0.01115044,  0.01227682,
        -0.00298353]),
 array([ 0.68329949, -0.75783565,  0.04887247,  0.01115044,  0.01227683,
        -0.00298354]),
 array([ 0.68329934, -0.75783582,  0.04887251,  0.01115044,  0.01227682,
        -0.00298353]),
 array([ 0.68329938, -0.75783578,  0.0488725 ,  0.01115044,  0.01227682,
        -0.00298353]),
 array([ 0.68329941, -0.75783574,  0.04887249,  0.01115044,  0.01227683,
        -0.00298353]),
 array([ 0.68329926, -0.75783591,  0.04887253,  0.01115044,  0.01227682,
        -0.00298353]),
 array([ 0.68329953, -0.75783562,  0.048